name: Docker Image CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  schedule:
    - cron: '0 1 * * SAT'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Get the tags version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF##*/}
    - name: Get the repo name (lower case)
      id: get_repo
      uses: ASzc/change-string-case-action@v1
      with:
        string: ${{ github.repository }}
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      with:
        version: latest
    - name: Builder instance name
      run: echo ${{ steps.buildx.outputs.name }}
    - name: Available platforms
      run: echo ${{ steps.buildx.outputs.platforms }}
    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64 #,linux/arm/v7,linux/arm64
        push: true
        tags: |
          ghcr.io/${{  steps.get_repo.outputs.lowercase }}:${{ steps.get_version.outputs.VERSION }}
          ghcr.io/${{ steps.get_repo.outputs.lowercase }}:latest
